### ISSUE TITLE
Update partnerUrl cache after saving

### ISSUE THREAD

**Issue by jvanveen** [VoIPGRID/vialer-js#103]
### File / Feature
2.0.13

### Expected behaviour
Login with partner.voipgrid.nl as platform URL. Change it to acceptatie.voipgrid.nl (you're logged out).
Change it back to partner.voipgrid.nl. A red warning should show, but it doesn't because partner.voipgrid.nl is still in the cache.

**Comment by ghost** [comment]
Fixed in develop
