### ISSUE TITLE
Storing username / password plain text in localStorage

### ISSUE THREAD

**Issue by JeroenBoersma** [VoIPGRID/vialer-js#112]
### Version

Vialer 2.0.16

### File / Feature

Entering username and password in the login screen.

### Expected behaviour

After logging in a token is loaded and saved in in localStorage.

### Actual behaviour

Username and password entered in the login screen are saved in localStorage in plain text.

### Stacktrace / Error message

No error message just the possibility to read the plain text password from the browser.

### Other info

We use external password tools nowadays to not have passwords stored inside browsers, this totally breaks this behavior.

**Comment by jvanveen** [comment]
Thank you for reporting this issue. We are aware of this issue and considering a token-based solution for this in the near future.

**Comment by ghost** [comment]
Version 3 in the develop branch has pbkdf2 encryption of localStorage data. This version is scheduled to be released later this year.
