### ISSUE TITLE
Availability options (YES/NO) overlap the box where they should be (Only on FF)

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/vialer-js#115]
### Version
2.0.15

### File / Feature

Availability (Only  on Firefox)

### Expected behaviour

The options YES and NO should be inside the box meant for them, or the box should be removed as it is in the Chrome version.

### Actual behaviour

The  dial button for the YES option is overlapping the box where it's supposed to be.

### Stacktrace / Error message

    {paste here}

### Other info

If the user clicks on the Options icon and waits for the options to appear, he can click again on the Vialer icon and then the bug is gone, since the box disappears. However, once the Availability menu collapses, if the user opens it again, the bug is back in place.

### Steps to reproduce
1. Log into Vialer
2 Click on Availability
3. Notice the overlap

### Screenshot
![availability options are out of the box](https://user-images.githubusercontent.com/29778372/33271357-4c24187e-d387-11e7-8092-4e2c295c9c55.jpg)

**Comment by ghost** [comment]
Fixed in develop (Firefox branch still not fully functional though)
