### ISSUE TITLE
Removing a fullstop and the "presence" reference within the Colleagues' refreshing mouseover

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/vialer-js#116]
### Version
2.0.15 on FF
2.0.16 on Chrome

### File / Feature

Colleagues Mouseover when refreshed

### Actual behaviour
Whenever a user clicks con the refresh button, the list of Colleagues gets updated. Before the new list is ready, a flashing icon appears in the shape of a cloud with an arrow pointing down. If the user does a mouseover this icon, the message "Waiting for presence information." appears.

### Expected behaviour

The message could be improved by removing the fullstop at the end of the sentence, since the context where it appears does not require an indication that it's the end of the sentence, and also for consistency with other messages that do not contain a fullstop at the end.
Also, the user most likely does not know anything about "presence" so this reference should be removed and leave the message "Waiting for information", or "Waiting for new information".

### Stacktrace / Error message

    {paste here}

### Steps to reproduce
1. login to Vialer
2. Click on the refresh button
3. Wait until the cloud icon appears
4. Place your mouse over the icon (not physically unless you want to scratch your screen :D)
5. Notice the punctuation/presence message

### Screenshot
![waiting for presence information has a redundant fullstop and also who knows what is presence](https://user-images.githubusercontent.com/29778372/33272364-3b73ec7c-d38a-11e7-870f-00fabf9c4808.jpg)

**Comment by ghost** [comment]
Fixed in develop
