### ISSUE TITLE
"Add C2D icon" is not activated by default after installing the plugin

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/vialer-js#118]
### Version
Beta 2.1.0 Firefox and 3.0.0

### Expected behaviour
After installing the plugin, the box "Add Click-to-Dial icons to websites" should be ticked by default.

### Actual behaviour
After installing the C2D plugin, the box for "Add Click-to-Dial icons to websites" is not ticked by default.

### Stacktrace / Error message

    {paste here}

### Other info
After installing the Click to Dial plugin the user still does not see the C2D icon in websites that show a telephone number.
This is because the option "Add Click-to-Dial icons to websites" is not activated by default after installing the plugin.

Same as https://voipgrid.atlassian.net/browse/GRID-5095

![add click to dial button to websites](https://user-images.githubusercontent.com/29778372/33719585-8087985c-db61-11e7-8487-dce884cffd8f.jpg)

**Comment by ghost** [comment]
Fixed in develop
