### ISSUE TITLE
Pressing Enter does not work to confirm user+pass login information

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/vialer-js#119]
### Version
Beta 2.1. and 3.0.0.

### File / Feature

Login

### Expected behaviour

The user should be able to hit enter to confirm his password entry.

### Actual behaviour

The user has to click on the OK button to confirm his password because hitting Enter does not register.

### Steps to reproduce
1. Download and install the plugin
2. Left click on the icon
3. Enter a username and password
4. Press Enter and notice how it does not confirm the login details

**Comment by ghost** [comment]
Fixed in develop (30.0.82)
