### ISSUE TITLE
Styling issues on the popup's edge on small screens/in small window sizes in Firefox

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/vialer-js#88]
### Version

2.1.0

### File / Feature

General styling

### Expected behaviour

Popup looks the same as on a big screen.

### Actual behaviour

![add-ons manager - firefox nightly_003](https://user-images.githubusercontent.com/1432901/31078056-f3e93d06-a780-11e7-9e16-c60fb31d6e55.png)

### Other info

Make your screen/firefox window small enough so the add-on icons are behind the >>-menu. For a second, the popup will display shorter than how it will eventually end up. The styling remains in the state of that one second.

**Comment by TomOffringa** [comment]
Only occurs in Firefox 57 (Beta). Will test again when FF 57 is released to make sure it isn't because of the beta version.
